### ISSUE TITLE
Heroku deployment unstable

### ISSUE THREAD

**Issue by dustinfast** [dustinfast/PTC-Sim#9]
Port binding fails with ADDRESS ALREADY IN USE and after a minute or two of runtime, memory usage exceeds 500mb limit (presumably as a result of multiple threads failing/restarting due to port bind issue).

Heroku web log output -
```
2018-11-23T18:28:09.088733+00:00 app[web.1]: Exception in thread Thread-15:
2018-11-23T18:28:09.088737+00:00 app[web.1]: Traceback (most recent call last):
2018-11-23T18:28:09.088739+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
2018-11-23T18:28:09.088741+00:00 app[web.1]:     self.run()
2018-11-23T18:28:09.088743+00:00 app[web.1]:   File "/app/lib_messaging.py", line 353, in run
2018-11-23T18:28:09.088745+00:00 app[web.1]:     sock.bind((BROKER, SEND_PORT))
2018-11-23T18:28:09.088747+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/socket.py", line 228, in meth
2018-11-23T18:28:09.088749+00:00 app[web.1]:     return getattr(self._sock,name)(*args)
2018-11-23T18:28:09.088751+00:00 app[web.1]: error: [Errno 98] Address already in use
```

Heroku main log -
```
2018-11-23T18:29:16.367777+00:00 heroku[web.1]: Process running mem=533M(104.3%)
2018-11-23T18:29:16.367829+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
```

**Comment by dustinfast** [comment]
Tried reducing number of concurrent locos to 1 (truncated `static/track/locos.json`) with no effect. 
Behavior suggests more than one instance of the application is starting?

**Comment by dustinfast** [comment]
Added better exeception handling - instead of erroring out on [Errno 98], exit. This still causes mem to fill up, and only one loco to work.
